/**
 * 
 */
package org.purewidgets.shared.events;

import java.util.ArrayList;


/**
 * Event listener for Input events generated by the 
 * {@link org.purewidgets.client.widgetmanager.instantplaces.client.widgetmanager.WidgetManager}.
 * 
 * @author Jorge C. S. Cardoso
 *
 */
public interface InputListener {
	
	/**
	 * Event triggered by the InteractionManager to signal
	 * input to this widget.
	 * 
	 * @param ie An InputEvent object.
	 */
	public void onInput(ArrayList<InputEvent> ie);
}
